# Enter your per-environment constants below

development: &default
  github_url: https://github.com/tardate/rgovdata
  site_github_url: https://github.com/tardate/rgovdata_site

production:
  <<: *default
  ga_id: UA-4894631-12
  
test:
  <<: *default